aws_region     = "us-east-1"
app_name       = "node-app"
instance_type  = "t3.micro"
ami_id         = "ami-0c02fb55956c7d316"
key_name       = "my-ssh-key"
db_username    = "postgres"
db_password    = "SuperSecurePassword123!"
